// Code generated by go-easy generate error code DO NOT EDIT.
// go-easy url: https://github.com/siskinc/go-easy
package mob_smssdk

func (e ErrorCode) Error() string {
	switch e {

	case ErrorCodeAppKeyEmpty:
		return "AppKey为空"

	case ErrorCodeAppKeyInValid:
		return "AppKey无效"

	case ErrorCodePhoneFormat:
		return "手机号码格式错误"

	case ErrorCodeRequestFrequently:
		return "请求校验验证码频繁（5分钟内同一个appkey的同一个号码最多只能校验三次）"

	case ErrorCodeServerVerifyNotOpen:
		return "没有打开服务端验证开关"

	case ErrorCodeVerifyCode:
		return "验证码错误"

	case ErrorCodeVerifyCodeEmpty:
		return "请求校验的验证码为空"

	case ErrorCodeZoneOrPhoneEmpty:
		return "国家代码或手机号码为空"

	}
	return "UNKNOWN"
}

func (e ErrorCode) String() string {
	switch e {

	case ErrorCodeAppKeyEmpty:
		return "ErrorCodeAppKeyEmpty"

	case ErrorCodeAppKeyInValid:
		return "ErrorCodeAppKeyInValid"

	case ErrorCodePhoneFormat:
		return "ErrorCodePhoneFormat"

	case ErrorCodeRequestFrequently:
		return "ErrorCodeRequestFrequently"

	case ErrorCodeServerVerifyNotOpen:
		return "ErrorCodeServerVerifyNotOpen"

	case ErrorCodeVerifyCode:
		return "ErrorCodeVerifyCode"

	case ErrorCodeVerifyCodeEmpty:
		return "ErrorCodeVerifyCodeEmpty"

	case ErrorCodeZoneOrPhoneEmpty:
		return "ErrorCodeZoneOrPhoneEmpty"

	}
	return "UNKNOWN"
}

func (e ErrorCode) ErrorCode() uint64 {
	return uint64(e)
}
